name: movie_list_app
description: A movie list application
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  retrofit: ^4.0.1
  dio: ^5.3.2
  json_annotation: ^4.8.1
  cached_network_image: ^3.2.3
  flutter_bloc: ^8.1.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  logger: ^2.0.1
  connectivity_plus: ^4.0.2
  hugeicons: ^0.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^7.0.8
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  flutter_lints: ^2.0.0
